name: End-to-end tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.18.0'
    - name: Install dependencies
      run: npm i
      
    - name: Run Cypress tests
      run: npx cypress run --browser chrome --headless --env allure=true
      
    - name: Reports Generate
      run: npm run allure:clear
    
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
        #id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN:  ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
